name: ChopTree2
main: me.Iso.ChopTree.ChopTree
version: 2.0
author: ellbristow
commands:
  ChopTree:
    description: Control the plugin
    aliases:
        ct
permissions:
  choptree.chop:
    description: Player can chop trees in one chop